version: "3.7"

services:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports: 
      - 8000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
    depends_on:
      - postgres

  postgress: 
    image: postgress:14
    container_name: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: develop
      POSTGRES_USER: postgres
      POSTGRES_DB: secret
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: